version: 2.1 

  
orbs: 
  aws-ecr: circleci/aws-ecr@6.12.2 
  aws-ecs: circleci/aws-ecs@1.2.0 

  
workflows: 
  setup_and_test: 
    jobs: 
      - aws-ecr/build-and-push-image: 
          name: "Build docker image for ecr" 
          account-url: AWS_ECR_ACCOUNT_URL 
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
          create-repo: true 
          dockerfile: ./Dockerfile 
          path: . 
          region: AWS_REGION 
          repo: aws-test 
          tag: "${CIRCLE_SHA1}" 

      - aws-ecs/deploy-service-update: 
          name: "Deploy newly create docker image to ECS" 
          requires: 
            - "Build docker image for ecr" 
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
          family: "aws-test" 
          cluster-name: "aws-test" 
          service-name: "aws-test" 
          container-image-name-updates: "container=aws-test,tag=${CIRCLE_SHA1}" 
          force-new-deployment: true 